name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Environment variables
env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  NODE_ENV: production

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Debug environment
      run: |
        echo "=== Environment Debug ==="
        pwd
        ls -la
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Checking package.json..."
        cat package.json | grep -A 10 -B 2 "vite"
        echo "Checking package-lock.json exists..."
        ls -la package-lock.json
    
    - name: Clean install dependencies
      run: |
        echo "=== Installing Dependencies ==="
        # Remove node_modules and package-lock if they exist
        rm -rf node_modules package-lock.json || true
        # Fresh install
        npm install
        echo "=== Installation Complete ==="
        echo "Checking node_modules..."
        ls -la node_modules/ | head -10
        echo "Checking .bin directory..."
        ls -la node_modules/.bin/ | grep vite || echo "No vite in .bin"
    
    - name: Verify Vite installation
      run: |
        echo "=== Vite Verification ==="
        echo "NPM list output:"
        npm list --depth=0 | grep vite || echo "Vite not found in npm list"
        echo "Direct package check:"
        ls -la node_modules/vite/ || echo "Vite package directory not found"
        echo "Binary check:"
        ls -la node_modules/.bin/vite || echo "Vite binary not found"
        echo "Version check:"
        ./node_modules/.bin/vite --version || echo "Cannot run vite --version"
    
    - name: Build application
      run: |
        echo "=== Building Application ==="
        echo "Trying multiple build methods..."
        
        # Method 1: Try npm run build
        if npm run build; then
          echo "✅ npm run build succeeded"
        else
          echo "❌ npm run build failed, trying direct binary..."
          
          # Method 2: Try direct binary path
          if ./node_modules/.bin/vite build; then
            echo "✅ Direct binary succeeded"
          else
            echo "❌ Direct binary failed, trying npx..."
            
            # Method 3: Try npx (will download if needed)
            if npx vite@5.4.21 build; then
              echo "✅ npx succeeded"
            else
              echo "❌ All build methods failed"
              echo "=== Final Diagnostics ==="
              echo "PATH: $PATH"
              echo "node_modules/.bin contents:"
              ls -la node_modules/.bin/ || echo "No .bin directory"
              echo "Vite package contents:"
              ls -la node_modules/vite/ || echo "No vite package"
              exit 1
            fi
          fi
        fi
      env:
        NODE_ENV: production
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Get deployment URL
      run: |
        echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
