name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Environment variables
env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Debug environment
      run: |
        echo "=== Environment Debug ==="
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Checking package.json for Vite..."
        grep -A 5 -B 5 '"vite"' package.json || echo "Vite not found in package.json"
        echo "Checking package-lock.json exists..."
        ls -la package-lock.json
    
    - name: Install dependencies
      run: |
        echo "=== Installing Dependencies ==="
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        
        # Try npm ci first (preferred for CI)
        if npm ci; then
          echo "✅ npm ci succeeded"
        else
          echo "❌ npm ci failed, trying npm install..."
          # Fallback to npm install
          npm install
        fi
        
        echo "=== Installation Complete ==="
        echo "Checking if Vite is installed..."
        npm list vite || echo "Vite not found in npm list"
    
    - name: Verify and fix Vite installation
      run: |
        echo "=== Vite Verification ==="
        echo "Checking Vite installation..."
        
        if [ -f "node_modules/.bin/vite" ]; then
          echo "✅ Vite binary found"
          ./node_modules/.bin/vite --version
        else
          echo "❌ Vite binary not found, installing manually..."
          npm install --save-dev vite@^5.4.21
          
          # Verify again
          if [ -f "node_modules/.bin/vite" ]; then
            echo "✅ Vite installed successfully"
            ./node_modules/.bin/vite --version
          else
            echo "❌ Failed to install Vite"
            exit 1
          fi
        fi
    
    - name: Build application
      run: |
        echo "=== Building Application ==="
        npm run build
        echo "=== Build Complete ==="
        echo "Checking build output..."
        ls -la dist/ || echo "No dist directory found"
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Get deployment URL
      run: |
        echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
